#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2016
#
# This file is in the public domain.
# 
#########################################################################
####

# source files in this project (main.cpp is automatically assumed)
SOURCES := RF24.cpp

# header files in this project
HEADERS := RF24.hpp nRF24L01.h

# other places to look for files for this project
SEARCH  := 

# set RELATIVE to the next higher directory 
# and defer to the appropriate Makefile.* there
RELATIVE := ..
include $(RELATIVE)/Makefile.due
